### ISSUE TITLE
Layout issue for bottom and top bar new resolutions like iPhone XS and Max

### ISSUE THREAD

**Issue by hananahmad** [TinyCrayon/TinyCrayon-iOS-SDK#28]
I have found this sdk very useful and I am thankful to Tiny for special efforts, there I find some layout issue for top and bottom bars please find some of your precious time to fix this one thanks.

**Comment by zengxinzhy** [comment]
It has been fixed in the latest version, thanks for catching this problem

**Comment by albertleal** [comment]
Hi, this is still happening updating the last version of cocoapods available.

Thanks @zengxinzhy !
