### ISSUE TITLE
Unable to Install/Download Library as website is down if anyone has the Framework Zip please share here

### ISSUE THREAD

**Issue by yousaf94** [TinyCrayon/TinyCrayon-iOS-SDK#46]

**Comment by mguadagnini** [comment]
Would be awesome if someone has, at least, a repo mirror or copy...

**Comment by yousaf94** [comment]
Yes I hope someone will help us on this

**Comment by rodrigoalvarez** [comment]
Please

**Comment by deeprathod** [comment]
Kindly have a look at the attachment. It might help.  @rodrigoalvarez  @yousaf94 @mguadagnini https://we.tl/t-UNh3CjYhZ5

**Comment by yousaf94** [comment]
@deeprathod Thank You.

**Comment by rodrigoalvarez** [comment]
@deeprathod legend!

**Comment by pracki93** [comment]
Thank you @deeprathod !
@yousaf94 @rodrigoalvarez were you able to run it cause I get an error:
Module compiled with Swift 4.2 cannot be imported by the Swift 5.4.2 compiler

**Comment by deeprathod** [comment]
@pracki93  Yes, I am also getting the same error! 

I did use this library 2 years back. So it was working fine with the previous SWIFT version I guess.

**Comment by dsmailes** [comment]
This is because the framework is pre-compiled. To use it with the latest Swift version we would need the source code, and the author is unavailable at the moment.

**Comment by ericcheungwork** [comment]
Thanks @deeprathod 

I can't use the library (same as other users). 
I posted by experience to [a question in stackoverflow](https://stackoverflow.com/questions/69221302/how-can-i-use-old-binary-library-tinycrayon-on-latest-ios-project).
Hope someone can help.

**Comment by zengxinzhy** [comment]
Many apologize for the late reply about this issue. I've fixed the migration issues to make sure the code works on Xcode 12 and Swift 5, and also make the source code open!

A lot of things happened in my life during the last 2-3 years: changing my job and started to work in a new country, getting married ect.. I was too exhausted to spare my time to maintain this repo.

I feel so sorry for your guys about not updating the release in time, so I decide to make it open source so that you will not have this risk any more.

BTW, due to the [infamous linking issue](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io) brought by using OpenCV which may not be completely built for Apple Arches, I'm still not able to figure out how to deploy this repo to CocoaPods after Xcode 12. 

**Please follow the new steps to install this SDK**, which have been updated in [README](https://github.com/TinyCrayon/TinyCrayon-iOS-SDK#installation)

**Comment by ericcheungwork** [comment]
Many many thanks for your help!
I want to say thank you wholeheartedly :)

**Comment by X901** [comment]
I still cannot use your library
after I did every steps 
I got this error 

```
clang: error: no such file or directory: '/Users/X901/Library/Developer/Xcode/DerivedData/RemoveBackground-awsqnsfmazciumgzolgoculjahxg/Build/Products/Debug-iphonesimulator/TCCore.framework/TCCore'

clang: error: no such file or directory: '/Users/X901/Library/Developer/Xcode/DerivedData/RemoveBackground-awsqnsfmazciumgzolgoculjahxg/Build/Products/Debug-iphonesimulator/TCMask.framework/TCMask'

Command Ld failed with a nonzero exit code

```
